myDream/popup/test_project/urls.py
from django.conf.urls.defaults import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'test_project.views.home', name='home'),
    # url(r'^test_project/', include('test_project.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)

myDream/urls.py
from django.conf.urls import url

# The '.' means the directory we are in ie myFrog
from . import views  # The file
from davesHappyFamily import signPost, logOn, smallHandlers, builder



from django.contrib.sitemaps.views import sitemap
from .sitemaps import StaticViewSitemap

sitemaps = {
    'static': StaticViewSitemap
}




# Help with sitemaps:
# https://docs.djangoproject.com/en/1.10/ref/contrib/sitemaps/#django.contrib.sitemaps.Sitemap


# This tells django which app the urls belong to
# when using the url tag var in an html file, see templates/myPolls/index.html.
app_name = 'myDream'


# Now we are going to use some generic views since many of our handlers
# were similar.  See the end of lesson 4 at:
# https://docs.djangoproject.com/en/1.10/intro/tutorial04/
# The 'IndexView, DetailView and ResultsView are classes now in views.py
# django expects the P to pass too be called <pk> for a generic as_view().


"""
help with regexp:
https://docs.python.org/2/library/re.html

(?:...)
A non-capturing version of regular parentheses. Matches whatever regular expression is
inside the parentheses, but the substring matched by the group cannot be retrieved
after performing a match or referenced later in the pattern.

(...)
Matches whatever regular expression is inside the parentheses, and indicates the start
and end of a group; the contents of a group can be retrieved after a match has been
performed, and can be matched later in the string with the \number special sequence,
described below. To match the literals '(' or ')', use \( or \), or enclose them inside a character class: [(] [)].
"""

"""
^	Match start of string	^Dear
eg r'^Dear' will match any string starting with the word Dear.
r'[^Dear]' will match anything but the word Dear.

$
Basically Davee the string before the $ must match.
eg  r'money$' will match any string ending in the word money.

Matches the end of the string or just before the newline at the
end of the string, and in MULTILINE mode also matches before a
newline. foo matches both 'foo' and 'foobar', while the regular
expression foo$ matches only 'foo'. More interestingly, searching
for foo.$ in 'foo1\nfoo2\n' matches 'foo2' normally, but 'foo1'
in MULTILINE mode; searching for a single $ in 'foo\n' will find
two (empty) matches: one just before the newline, and one at the
end of the string.

(?P<name>...)
Similar to regular parentheses, but the substring matched by the group is accessible
via the symbolic group name name. Group names must be valid Python identifiers, and
each group name must be defined only once within a regular expression. A symbolic
group is also a numbered group, just as if the group were not named.
And it goes on and on in the docs...

url(r'^blog/(?P<slug>[\w-]+)/$', 'myapp.views.blog_detail', name='blog_detail'),
"""

PAGE_RE = r'(?P<pk>[a-zA-Z0-9\_-]+)*/*'

urlpatterns = [

    # Just using this for testing stuff.
    # File views.py, class TestView in that file, imported above.
    url('test/',views.TestView.as_view(), name='test'),
    # or you can do this
    #url(r'^test/$',views.TestView.as_view(), name='test'),


    url('logOn/', logOn.logOn, name='logOn'),
    url('logOut/', smallHandlers.logOut, name='logOut'),

    # forgot name or password, this now handles both.
    url('forgot/', smallHandlers.forgot, name='forgot'),

    # The file 'signPost.py' must be in the same directory as this url mapper.
    # Works with forms.py, class UserInfoForm
    #        File signPost.py signPost() in that file.  file imported above.
    url('signPost/', signPost.signPost, name='signPost'),

    # Build your own web page in less that 5 seconds.
    url('fiveSeconds/', smallHandlers.FiveSeconds.as_view(), name='fiveSeconds'),

    url('message/', views.Message.as_view(), name='message'),

    url('yourProfile/', views.YourProfile.as_view(), name='yourProfile'),
    url('changePassword/', smallHandlers.changePassword, name='changePassword'),

    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
    name='django.contrib.sitemaps.views.sitemap'),

    url('books/', smallHandlers.books, name='books'),



# This has been temporarily pointed at my webflow art page.  Dec 29/18
    url('artForSale/', smallHandlers.artForSale, name = 'artForSale'),
# I use this one for updating in the background
    url('artForSale2/', smallHandlers.artForSale2, name = 'artForSale2'),

    url('paymentReceived/', smallHandlers.paymentReceived, name='paymentReceived'),

    url(r'^contact/$', smallHandlers.contact, name='contact'),


# This is a list of my dvd/s etc that I have for sale.  Available for download.
    url(r'^davesList/$', smallHandlers.davesList, name='davesList'),


    url(r'^guitarVideos/$', smallHandlers.guitarVideos, name='guitarVideos'),

    url(r'^baby/$', smallHandlers.baby, name='baby'),



    url(r'^sendExcel/$', smallHandlers.sendExcel, name = 'sendExcel'),

    url(r'^sendTrades/$', smallHandlers.sendTrades, name = 'sendTrades'),

    url(r'^sendTrades2/$', smallHandlers.sendTrades2, name = 'sendTrades2'),

    url(r'^stockMarketPortfolio/$', smallHandlers.stockMarketPortfolio, name='stockMarketPortfolio'),


    url(r'^sendStockMarketBook/$', smallHandlers.sendStockMarketBook, name='sendStockMarketBook'),


    url(r'^survives/$', smallHandlers.survives, name='survives'),

    url(r'^vehicle/$', smallHandlers.vehicle, name='vehicle'),

    url(r'^cats/$', smallHandlers.cats, name='cats'),

    url(r'^gout/$', smallHandlers.gout, name='gout'),

    url(r'^horse/$', smallHandlers.horse, name='horse'),

    url(r'^dunk/$', smallHandlers.dunk, name='dunk'),

    url(r'^money/$', smallHandlers.money, name='money'),

    url(r'^phone/$', smallHandlers.phone, name='phone'),


# builder
# This is where I build my clients web sites.  NOT HAPPENING SCRAP THIS ONE.
# I'm building my clients web sites at webFlow.com  They will use webFlows servers.
    #url(r'^builder/$', builder.davesBuilder, name='davesBuilder'),



# I am now using this mapper to redirect to my webflow page, as I won't
# be using this for mobirise (bootstrap) anymore.  Scraping mobirise.
# So FOR MY GOOGLE AD the client clicks on theHyperDream.com/myDream/websitebuilder
# and this redirects them to https://david-potschkas-five-star-project.webflow.io/

   url(r'^webSiteBuilder/$', builder.webSiteBuilder, name='webSiteBuilder'),





###################### End daveBuilder


    # This one must be last.  It is now in superDream/url.py
    #   file views.py, class IndexView
    #url(PAGE_RE, views.IndexView.as_view(), name='index')

]

"""
url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
"""




"""
Note that the name of the matched pattern in the regexes of the second
and third patterns has changed from <question_id> to <pk> above.
Anything inside <hello I'm inside> is passed to the handler.

The old way.
urlpatterns = [
    # ex: /myPolls/
    url(r'^$', views.index, name='index'),

    # ex: /myPolls/5/
    url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),

    # ex: /myPolls/5/results/
    url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),

    # ex: /myPolls/5/vote/
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

"""

sales/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^ipnListener/$', views.ipnListener, name='ipnListener'),
    url(r'^sendProduct/$', views.sendProduct, name='sendProduct'),
]

superDream/urls.py
from django.conf.urls import url, include
from django.contrib import admin


# The sslVerify is to verify my ssl certificate.
# My ssl server NameCheap says they want this file to render (BFABF40A0DA7138F42243A3C8C380CA4.txt)
# when they type this into the address bar:
# http://thehyperdream.com/.well-known/pki-validation/BFABF40A0DA7138F42243A3C8C380CA4.txt
# I put that txt file in the /home/timetable/superDream/myDream/templates/myDream and it worked.

# Also see here:
"""
The certificate file was sent to: dave@thehyperdream.com you can also download it via the
following link: https://ap.www.namecheap.com/domains/ssl/certificatedownload/3014108/DetailsPagee
Please keep in mind that once the certificate is issued, it is necessary to install it on your hosting server.
The guide on the certificate installation for most common server types can be found here:
https://www.namecheap.com/support/knowledgebase/article.aspx/795/69/how-to-install-ssl-certificates
To check if the certificate is installed correctly, you can use this tool: https://decoder.link/sslchecker
"""
from myDream import sslVerify

# I needed this file to get the index view working.
from myDream import views

"""
from django.contrib.sitemaps.views import sitemap
from myDream.sitemaps import StaticViewSitemap

sitemaps = {
    'static': StaticViewSitemap
}
"""

urlpatterns = [
    #url(r'^paypal/', include('paypal.standard.ipn.urls')),

    #url(r'^sitemap/.xml$', sitemap, {'sitemaps': sitemaps},
    #name='django.contrib.sitemaps.views.sitemap'),

    url(r'^myDream/', include('myDream.urls'), name = 'myDream'),
    #url(r'^myDream/', include('myDream.urls')),

    url(r'^sales/', include('sales.urls')),
    url(r'^admin/', admin.site.urls),

    # This is to verify my ssl certificate.                                       file.function
    url(r'^.well-known/pki-validation/AD0AC50BCB5650CAA8781523EEA222DC.txt', sslVerify.sslVerify, name='sslVerify'),

    # CAUTION:  This url MUST BE LAST in this list.
    url('^$', views.IndexView.as_view(), name='index'),
]

myDream/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils.encoding import python_2_unicode_compatible

from django.utils import timezone

# Create your models here.

# CAUTION:  All fields must have a value if no default is given.

@python_2_unicode_compatible  # For python 2 support.
class User(models.Model):

# This is a hashpass and contains the algo$iterations$salt$hash.
    password = models.CharField(max_length=200)
    userName = models.CharField(max_length=200)

# How many votes you have made so far.
    numVotes = models.IntegerField(default=0)
    email = models.CharField(max_length=200)

# Don't use these they don't see the admin page.
# verbose_name='date_user_joined', auto_now=True

# Give it a better name for the admin db label date_user_joined
    created = models.DateTimeField('date_user_joined', default=timezone.now())

# returns a string instead of a reference to an object.
# You also need this for the decorator above.
# You could return any of the char fields above to the view.py
    def __str__(self):
#       'pass'
# CAUTION: Don't put 'pass' in here or the interprater will fuck up
# trying to return a non unicode object.
        return self.userName



################### End User




@python_2_unicode_compatible  # For python 2 support.
class PendingUser(models.Model):

# This is a hashpass and contains the algo$iterations$salt$hash.
    password = models.CharField(max_length=200)
    pendingUserName = models.CharField(max_length=200)

    email = models.CharField(max_length=200)


# Don't use these they don't see the admin page.
# verbose_name='date_user_joined', auto_now=True

# Give it a better name for the admin db label date_user_joined
    created = models.DateTimeField('date_pendingUser_joined', default=timezone.now())

# returns a string instead of a reference to an object.
# You also need this for the decorator above.
# You could return any of the char fields above to the view.py
    def __str__(self):
        'pass'
# CAUTION: Don't put 'pass' in here or the interprater will fuck up
# trying to return a non unicode object.
        return self.pendingUserName



################### End PendingUser



"""

To clear the sessions db I tried:
python manage.py clearsessions
It did not work because chrome remembers them for a spell.
It worked for firefox.


Some ways to access the db, there are 3.  I will use the first way below.


But first see this; interacting with more than one db.
NO DON'T, I'm not using multiple db, just multiple tables.
https://docs.djangoproject.com/en/1.10/topics/db/multi-db/


1.  Executing custom SQL directly

This is how I am going to do it.  It is the most robust and you
actually access the db directly.

See here three quarters of the way down the page:
https://docs.djangoproject.com/en/1.10/topics/db/sql/


Sometimes even Manager.raw() isn't quite enough: you might need to perform
queries that don't map cleanly to models, or directly execute UPDATE, INSERT,
or DELETE queries.

In these cases, you can always access the database directly, routing around
the model layer entirely.

The object django.db.connection represents the default database connection.
To use the database connection, call connection.cursor() to get a cursor
object. Then, call cursor.execute(sql, [params]) to execute the SQL and
cursor.fetchone() or cursor.fetchall() to return the resulting rows.

For example:

from django.db import connection

def my_custom_sql(self):
    with connection.cursor() as cursor:
        cursor.execute("UPDATE bar SET foo = 1 WHERE baz = %s", [self.baz])
        cursor.execute("SELECT foo FROM bar WHERE baz = %s", [self.baz])
        row = cursor.fetchone()

    return row
Note that if you want to include literal percent signs in the query,
you have to double them in the case you are passing parameters:

cursor.execute("SELECT foo FROM bar WHERE baz = '30%'")
cursor.execute("SELECT foo FROM bar WHERE baz = '30%%' AND id = %s", [self.id])
If you are using more than one database, you can use django.db.connections
to obtain the connection (and cursor) for a specific database.
django.db.connections is a dictionary-like object that allows you
to retrieve a specific connection using its alias:

from django.db import connections
cursor = connections['my_db_alias'].cursor()
# Your code here...

By default, the Python DB API will return results without their
field names, which means you end up with a list of values, rather
than a dict. At a small performance and memory cost, you can return
results as a dict by using something like this:


2. Perform raw SQL queries.  See the same docs as above.


3.  This reference has lots of commands and stuff you can use for above.


# See here:  https://docs.djangoproject.com/en/1.9/ref/models/querysets/#values-list
# flat takes it out of the list and turns it into a string, only good
for one object.

An example from my logOn()/handler.

dbPass = PendingUser.objects.values_list('pendingUserName','password',
'email', 'created').filter(pendingUserName = userName)
here is wat dbPass looks like, a tuple in a list.

<QuerySet [(u'bill', u'pbkdf2_sha256$30000$6FGO4mYDlJdQ$99lm/cor6XB5ltN8lGbp8ApfluXu+HSbXs02fWdrcKU=',
u'b@b.com', datetime.datetime(2016, 11, 19, 20, 28, 17, 890930, tzinfo=<UTC>))]>









"""

myDream/popup/popup_forms/models.py
# No models in this app. The models.py required to run Django tests

myDream/forms.py
from django import forms



class ChangePasswordForm(forms.Form):
    email = forms.EmailField(label = 'Your Email', max_length=200)
    oldPassword = forms.CharField(label = 'Your Old Password', max_length=32, widget=forms.PasswordInput)
    newPassword = forms.CharField(label = 'Your New Password', max_length=32, widget=forms.PasswordInput)
    newPasswordAgain = forms.CharField(label = 'Your New Password again', max_length=32, widget=forms.PasswordInput)



class ContactForm(forms.Form):
    contact_name = forms.CharField(required=True)
    contact_email = forms.EmailField(required=True)
    content = forms.CharField(required=True, widget=forms.Textarea)

    pledgeAmount = forms.IntegerField(required=True, min_value=0)

    #stopRobot = forms.CharField(required=True)



    def __init__(self, *args, **kwargs):
        super(ContactForm, self).__init__(*args, **kwargs)
        self.fields['contact_name'].label = "Your name:"
        self.fields['contact_email'].label = "Your email:"
        self.fields['content'].label = "How may I help you?"

        self.fields['pledgeAmount'].label = "How much money (in $US) are you thinking about investing?  (current minimum is $10k).  Please enter zero if you are contacting me for other reasons..."

        #self.fields['stopRobot'].label = "What is 6*3?"






######################### End ContactForm


class ForgotForm(forms.Form):
    email = forms.EmailField(label = 'Your Email', max_length=200)



class LogOnForm(forms.Form):

    userName = forms.CharField(label='Your Nickname', max_length=100)
    password = forms.CharField(label = 'Your Password', max_length=32, widget=forms.PasswordInput)



# I'm calling the user's name, nickname instead, it is funner.
class UserInfoForm(forms.Form):
    """For a new user to sign up."""

    userName = forms.CharField(label='Your Nickname', max_length=100)
    email = forms.EmailField(label = 'Your Email', max_length=200)


class SurvivesForm(forms.Form):
    email = forms.EmailField(label = 'Your Email', max_length=200)

myDream/templates/myDream/changePassword.html
<!DOCTYPE html>

{% load static %}

<html>
<!-- This is my web page template using flex for sizing. The following must be under the html tag.   -->
<!-- c:/Daves_Python_Progrmas/wiki/whatdoesthefroggot/templates_local/flexPageTemplate.html      -->





    <head>

		<title>ChangePassword</title>



		<link rel="stylesheet" type="text/css" href="{% static 'myDream/dreamStyleSheet.css' %}">


<meta name="description" content="self help">
<meta name="keywords" content="thd, THD, theHyperDream, thehyperdream, the hyperdream, the hyper dream,
the dream, dream, self help, help me, dream boy, dream girl,
motivate, motivate anyone, love, health, wealth, happiness,
subliminal questions, motivation questions, motivation, ideas, great ideas, guru,
hope, get off drugs, get my teenager off drugs, subliminal intervention, subliminal, intervention, quit drugs, help others, help all,
help ">
<meta name="author" content="David H Potschka">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

		<style>

			#main { display: flex; }
			#main > article { order: 2; min-width: 12em; flex:1; }   /* 12 em is 192px plus nav and aside equals 592px */
			#main > nav     { order: 1; width: 200px; }              /* that is why @media has a max width of 600px */
			#main > aside   { order: 3; width: 200px; }

			/*

			As an added bonus, the columns will all be equal-height by default, and the main content will
			be as wide as necessary to fill the screen. Additionally, this can then be combined with media
			queries to switch to an all-vertical layout on narrow screens:

			*/

			@media all and (max-width: 600px) {
			/* Too narrow to support three columns */
			#main { flex-flow: column; }
			#main > article, #main > nav, #main > aside {
			/* Return them to document order */
			order: 0; width: auto;
			  }
			}

            body {
                    background-image: url("/static/myDream/webImages/asses.jpg");
                     background-repeat: no-repeat;
                      background-size: 100% 100%;
                 }




		</style>


<!-- Facebook Pixel Code -->
<script>
!function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
document,'script','https://connect.facebook.net/en_US/fbevents.js');
fbq('init', '1262471543795678'); // Insert your pixel ID here.
fbq('track', 'PageView');
</script>
<noscript><img height="1" width="1" style="display:none"
src="https://www.facebook.com/tr?id=1262471543795678&ev=PageView&noscript=1"
/></noscript>
<!-- DO NOT MODIFY -->
<!-- End Facebook Pixel Code -->


    </head>




	<body>

		<header>
<!--
<script type="text/javascript" src="/static/myDream/js/butImages.js"></script>
<a href="http://www.thehyperdream.com/"><img id="logoNet" height="15%" width="15%" src="/static/myDream/webImages/buttons/logoNet/hyperDreamLogo1.jpg" onmouseover="getid(this);" /></a>
-->

<a href="http://www.thehyperdream.com/"><img id="logoPic" style="margin-left:20px; margin-top:20px" height="11.11%" width="11.11%" src="/static/myDream/theArt/thd3f.png" /></a>

<br>

		</header>


		<div id='main'>


			<nav>


			</nav>



			<article>



CHANGE YOUR PASSWORD
Your password must be at least 8 characters long and less than 31 characters long.

<form action="{% url 'myDream:changePassword'%}" method="post">

<!-- Cross Site Request Forgeries.  Stops hackers, from django.  Lesson 4 -->
    {% csrf_token %}

<!-- The form is filled in automatically by forms.py, class
UserInfoForm -->

    <table>
    {{ form.as_table }}
    </table>
    <br><br>

    <input type="submit" value="Change My Password">
</form>

<span style="color:blue;margin-left:39px;">{{errorMessage}}</span>


<br>
<img src="{% static '/myDream/webImages/eyeN.jpg' %}" width='70%' height='70%' >

<br>
{{errorMessage2}}
<br>
{{errorMessage3}}
<br>
{{errorMessage4}}


			</article>



			<aside>


			</aside>


		</div>


		<footer>


		</footer>






    </body>



</html>

myDream/templates/myDream/signUp.html
<!DOCTYPE html>

{% load static %}

<html>
<!-- This is my web page template using flex for sizing. The following must be under the html tag.   -->
<!-- c:/Daves_Python_Progrmas/wiki/whatdoesthefroggot/templates_local/flexPageTemplate.html      -->

    <head>

		<title>Sign Up</title>


<meta name="description" content="Now is the time!">
<meta name="keywords" content="thd, THD, theHyperDream, thehyperdream, the hyperdream, the hyper dream,
the dream, dream, self help, help me, dream boy, dream girl,
motivate, motivate anyone, love, health, wealth, happiness,
subliminal questions, motivation questions, motivation, ideas, great ideas, guru,
hope, get off drugs, get my teenager off drugs, subliminal intervention, subliminal, intervention, quit drugs, help others, help all,
help ">
<meta name="author" content="David H Potschka">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

		<style>

			#main { display: flex; }
			#main > article { order: 2; min-width: 12em; flex:1; }   /* 12 em is 192px plus nav and aside equals 592px */
			#main > nav     { order: 1; width: 200px; }              /* that is why @media has a max width of 600px */
			#main > aside   { order: 3; width: 200px; }

			/*

			As an added bonus, the columns will all be equal-height by default, and the main content will
			be as wide as necessary to fill the screen. Additionally, this can then be combined with media
			queries to switch to an all-vertical layout on narrow screens:

			*/

			@media all and (max-width: 600px) {
			/* Too narrow to support three columns */
			#main { flex-flow: column; }
			#main > article, #main > nav, #main > aside {
			/* Return them to document order */
			order: 0; width: auto;
			  }
			}


            body {
                    background-image: url("/static/myDream/webImages/asses.jpg");
                     background-repeat: no-repeat;
                      background-size: 100% 100%;
                 }



		</style>


<!-- Facebook Pixel Code -->
<script>
!function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
document,'script','https://connect.facebook.net/en_US/fbevents.js');
fbq('init', '1262471543795678'); // Insert your pixel ID here.
fbq('track', 'PageView');
</script>
<noscript><img height="1" width="1" style="display:none"
src="https://www.facebook.com/tr?id=1262471543795678&ev=PageView&noscript=1"
/></noscript>
<!-- DO NOT MODIFY -->
<!-- End Facebook Pixel Code -->


    </head>

	<body>

		<header>

<!--
<script type="text/javascript" src="/static/myDream/js/butImages.js"></script>
<a href="http://www.thehyperdream.com/"><img id="logoNet" height="15%" width="15%" src="/static/myDream/webImages/buttons/logoNet/hyperDreamLogo1.jpg" onmouseover="getid(this);" /></a>
<br><br>
-->
		</header>


		<div id='main'>


			<nav>


			</nav>




			<article>


Welcome to the signup page!
<br>
Please enter your email address and your name.
<br>
We will send you a verification email and a password
<br>
so you can continue onto the site.
<br><br><br>

Cheers, <br><br>

Dave <br><br><br>


<!--
1.  Do you need to motivate someone?  <br><br>

2.  Do you want to learn a set of questions and answers  <br>
that result in a successful subliminal intervention?  <br><br>

3.  Do you have employees, clients, friends, strangers or family members <br>
who need to be put on the correct energized path?  <br><br>

4.  Do you need to get yourself re-engaged with that zest for life?<br><br>

If you answered yes to any of the above questions <br>
then you need to read the book: <br>
"Get My Teenager Off Drugs" <br><br>

Get immediate access to the book by entering your name and email below!  <br><br>

No credit card required.<br><br>
-->


<form action="{% url 'myDream:signPost'%}" method="post">

<!-- Cross Site Request Forgeries.  Stops hackers, from django.  Lesson 4 -->
    {% csrf_token %}

<!-- The form is filled in automatically by forms.py, class
UserInfoForm -->

    <table>
    {{ form.as_table }}
    </table>
    <br><br>

    <input type="submit" value="Thank You">
</form>

<span style="color:red;margin-left:39px;">{{nameTakenMessage}}</span>

<img src="{% static '/myDream/webImages/roseN.jpg' %}" width='894' height='470'><br>
<img src="{% static '/myDream/webImages/greenLifeN.jpg' %}" width='70%' height='70%' >



			</article>



			<aside>


			</aside>


		</div>


		<footer>


		</footer>






    </body>


<!--

ERROR: DJANGO WILL actually try to load the loaders in these comments
and they will cause errors.  So I have removed the first '%' from
each loader.

NOTES AND OTHER WAYS TO DO FORMS...

You can generate a form from a generic class SignUpView
but it's generally better to generate it from a class
UserInfoForm (my name) at forms.py see above.

<form action="{ url 'myFrog:signPost'%}" method="post">
    { csrf_token %}

The HTML Label Element ( <label> ) represents a caption for an
item in a user interface. It can be associated with a control
either by placing the control element inside the <label>
element, or by using the for attribute. Such a control is
called the labeled control of the label element.Jun 27, 2016

for my UserInfoForm class...

Note that each form field has an ID attribute set to id_<nickname>,
which is referenced by the accompanying label tag. This is important
in ensuring that forms are accessible to assistive technology such
as screen reader software.

    {{ form }}
    <label for="nickname">Your Nickname:</label>
    <input id="nickname" type="text" name="userName" value="{{ userName }}" maxlength="100" required>
    <input type="submit" value="Sign Up Super Super Cool">

</form>
-->




<!--
{ if error_message %}<p><strong>{{ error_message }}</strong></p>{ endif %}
-->

<!--
{{ error_message }}
{{ comment }}
{{ userNameCool }}

<form action="{ url 'myFrog:signPost'%}" method="post">

<table>

	<tr>
		<td class="label">
			<span style='background:white;'>UserName</span>
		</td>

		<td>
			<input type="text" name="userName" value={{userName}}>
		</td>

		<td class="error">

			{{userError | safe}}
		</td>

	</tr>

</table>

<input type="submit" value="Sign Up Super Super Cool!" />

</form>
-->

</html>